name: Release Package

on:
  pull_request:
    paths-ignore:
      - "README.md"
      - "docs/**"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/PULL_REQUEST_TEMPLATE.md"

jobs:
  create_release:
    uses: fullstack-devops/actions/.github/workflows/create-release.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: create_release
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup awesome-ci
        uses: fullstack-devops/awesome-ci-action@main
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"

      - name: install packages
        run: yarn
      - name: build applikation
        run: yarn run build

      - name: dryrun publish
        working-directory: dist/ng-ui-frame
        run: |
          yarn version ${{ needs.generate_infos.outputs.version }}
          yarn publish -dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish release
        run: awesome-ci release publish -releaseid "${{ needs.create_release.outputs.releaseid }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
